name: Build Applications

on:
  workflow_dispatch:
    inputs:
      build_ios:
        description: 'Build iOS IPA'
        type: boolean
        default: true

jobs:
  build_ios:
    runs-on: macos-latest
    if: ${{ inputs.build_ios }}

    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4

      - name: 📀 • Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 💾 • Cache Node Modules
        uses: actions/cache@v4
        with:
          path: app/node_modules
          key: node-modules-${{ hashFiles('app/package.json') }}
          restore-keys: |
            node-modules-

      - name: 🗂️ • Install Node Dependencies
        run: npm install --no-package-lock --legacy-peer-deps

      - name: 💾 • Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            app/ios/Pods
            ~/.cocoapods
          key: pods-${{ hashFiles('app/ios/Podfile.lock') }}
          restore-keys: |
            pods-

      - name: 🍫 • Install CocoaPods
        run: |
          cd ios
          pod install

      - name: 🏗️ • Build iOS
        run: |
          cd ios
          xcodebuild -workspace Movix.xcworkspace \
                     -scheme "Movix" \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -derivedDataPath ./build \
                     IPHONEOS_DEPLOYMENT_TARGET=15.1 \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGN_IDENTITY="" \
                     ENABLE_USER_SCRIPT_SANDBOXING=NO

      - name: 📦 • Bundle IPA
        run: |
          cd ios
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/Movix.app Payload/
          zip -r Movix.ipa Payload
          mv Movix.ipa build/Movix.ipa
          rm -rf Payload

      - name: 🌍 • Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Movix
          path: app/ios/build/Movix.ipa
          if-no-files-found: error
